baseURL = 'https://lakeshorelabs.ai/'
title = 'Lakeshore Labs'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

# Language configuration
[languages]
  [languages.en]
    contentDir = 'content/en'
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Lakeshore Labs'
    weight = 1
    [languages.en.params]
      description = "Stop Experimenting. Start Scaling with Custom AI. Proven Solutions. Guaranteed ROI."
      author = "Lakeshore Labs"
      email = "hello@lakeshorelabs.ai"
      
  [languages.vi]
    contentDir = 'content/vi'
    languageCode = 'vi-VN'
    languageDirection = 'ltr'
    languageName = 'Tiếng Việt'
    title = 'Lakeshore Labs'
    weight = 2
    [languages.vi.params]
      description = "Ngừng Thử Nghiệm. Bắt Đầu Mở Rộng với AI Tùy Chỉnh. Giải Pháp Đã Được Kiểm Chứng. ROI Được Đảm Bảo."
      author = "Lakeshore Labs"
      email = "hello@lakeshorelabs.ai"
      
  [languages.ar-OM]
    contentDir = 'content/ar-OM'
    languageCode = 'ar-OM'
    languageDirection = 'rtl'
    languageName = 'العربية العُمانية'
    title = 'Lakeshore Labs'
    weight = 3
    [languages.ar-OM.params]
      description = "توقف عن التجريب. ابدأ بالتوسع مع الذكاء الاصطناعي المخصص. حلول مثبتة. عائد استثمار مضمون."
      author = "Lakeshore Labs"
      email = "hello@lakeshorelabs.ai"

# SEO and metadata
[params]
  fingerprint = true  # Enable asset fingerprinting for better cache busting

# Enable features
enableRobotsTXT = true
enableGitInfo = false

# Goldmark configuration for Mermaid diagrams
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Output settings
[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML"]

# Build settings
[build]
  writeStats = false

# Minification
[minify]
  disableHTML = false
  disableCSS = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false

# Menu configuration for English
[[languages.en.menus.main]]
  identifier = "solutions"
  name = "Solutions"
  url = "#solutions"
  weight = 10

[[languages.en.menus.main]]
  identifier = "process"
  name = "Process"
  url = "#process"
  weight = 20

[[languages.en.menus.main]]
  identifier = "faq"
  name = "FAQ"
  url = "#faq"
  weight = 40

# [[languages.en.menus.main]]
#   identifier = "projects"
#   name = "Projects"
#   url = "/projects/"
#   weight = 50

# [[languages.en.menus.main]]
#   identifier = "blog"
#   name = "Blog"
#   url = "/posts/"
#   weight = 60

# [[languages.en.menus.main]]
#   identifier = "team"
#   name = "Team"
#   url = "/team/"
#   weight = 70

# Menu configuration for Vietnamese
[[languages.vi.menus.main]]
  identifier = "solutions"
  name = "Giải Pháp"
  url = "#solutions"
  weight = 10

[[languages.vi.menus.main]]
  identifier = "process"
  name = "Quy Trình"
  url = "#process"
  weight = 20

[[languages.vi.menus.main]]
  identifier = "faq"
  name = "Câu Hỏi"
  url = "#faq"
  weight = 40

# [[languages.vi.menus.main]]
#   identifier = "projects"
#   name = "Dự Án"
#   url = "/projects/"
#   weight = 50

# [[languages.vi.menus.main]]
#   identifier = "blog"
#   name = "Blog"
#   url = "/posts/"
#   weight = 60

# Menu configuration for Omani-Arabic
[[languages.ar-OM.menus.main]]
  identifier = "solutions"
  name = "الحلول"
  url = "#solutions"
  weight = 10

[[languages.ar-OM.menus.main]]
  identifier = "process"
  name = "العملية"
  url = "#process"
  weight = 20

[[languages.ar-OM.menus.main]]
  identifier = "faq"
  name = "الأسئلة الشائعة"
  url = "#faq"
  weight = 40

# [[languages.ar-OM.menus.main]]
#   identifier = "projects"
#   name = "المشاريع"
#   url = "/projects/"
#   weight = 50

# [[languages.ar-OM.menus.main]]
#   identifier = "blog"
#   name = "المدونة"
#   url = "/posts/"
#   weight = 60

# Hugo version requirement
[module]
  [module.hugoVersion]
    min = "0.147.0"
    extended = true

# Module configuration for assets
[[module.mounts]]
  source = "assets"
  target = "assets"

[[module.mounts]]
  source = "static"
  target = "static"

# Image processing configuration
[imaging]
  quality = 85
  resampleFilter = "lanczos"
  anchor = "smart"